version: '2'
services:
  web:
    image: 'fgrehm/sls-web:v0.1.0'
    command: serve
  worker:
    image: 'fgrehm/sls-web:v0.1.0'
    command: work
  dev:
    build:
      context: '../'
      dockerfile: 'ops/Dockerfile.dev'
    image: 'fgrehm/sls-web:dev'
    volumes:
      - '../:/workspace'
      - 'gocache:/root/.cache/go-build'
      - 'gomodcache:/go/pkg/mod'
  mongo:
    image: 'mongo:4.4.8'
  rabbitmgmt:
    image: 'rabbitmq:3.8.8-management'
