# vi: ft=dockerfile
FROM golang:1.17.0

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
              bzip2 \
              curl \
              g++ \
              gcc \
              git \
              graphviz \
              libc6-dev \
              make \
              pkg-config \
              xz-utils \
              ca-certificates \
              nodejs \
              npm \
              python \
    && rm -rf /var/lib/apt/lists/* \
    && npm install -g yarn

RUN go install github.com/jteeuwen/go-bindata/go-bindata@v3.0.7 \
    && go install github.com/cespare/reflex@v0.3.0

VOLUME /workspace
WORKDIR /workspace
ENV PATH "./node_modules/.bin:$PATH"
